config/routes.rb
WorkLog::Application.routes.draw do
  get "reports/index"
  post "reports/multiple_update"

  root :to => "plans#dashboard"
  resources :plans do
    collection do
      get :dashboard
      get :overview
      post :multiple_update
    end
  end

  devise_for :users

end

app/models/plan.rb
class Plan
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  field :date_for, :type => Date
  field :actual_log, :type => String
  field :report_log, :type => String
  field :extra_hours, :type => String

  belongs_to :user

  class << self
    def today
      plan = where(:date_for => Date.today).first
      unless plan
        plan = new(:date_for => Date.today)
      end
      plan
    end

    def yesterday
      where(:date_for.ne => Date.today).desc(:date_for).first
    end

    def last_two
      [yesterday, today]
    end

  end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :plans

  def name
    email.split('@').first.split('.').map(&:capitalize).join(' ')
  end

  def can_manage?
    if email =~ /dilyara/
      true
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
    redirect_to(overview_plans_url) && return if current_user.can_manage?
    @plans = current_user.plans.last_two
    respond_to do |format|
      format.html
      format.xml  { render :xml => @plans }
      format.txt
    end
  end

  def overview
    @users = User.where(:email.ne => current_user.email)
  end



  def multiple_update
    params[:plans].each do |id, data|
      if current_user.can_manage?
        plan = Plan.criteria.for_ids(id).first
      else
        plan = current_user.plans.criteria.for_ids(id).first
      end
      if plan
        plan.update_attributes(data)
      else
        if current_user.can_manage?
          plan = Plan.create(data.merge(:date_for =>Date.today))
        else
          plan = current_user.plans.create(data.merge(:date_for =>Date.today))
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to(dashboard_plans_url, :notice => 'Plan was successfully updated.') }
      format.xml  { head :ok }
    end
  end

  def index
    @plans = current_user.plans.desc(:date_for).paginate(params)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plans }
    end
  end

  def show
    @plan = current_user.plans.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  def new
    @plan = current_user.plans.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  def edit
    @plan = current_user.plans.find(params[:id])
  end

  def create
    @plan = current_user.plans.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to(@plan, :notice => 'Plan was successfully created.') }
        format.xml  { render :xml => @plan, :status => :created, :location => @plan }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @plan = current_user.plans.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to(@plan, :notice => 'Plan was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @plan = current_user.plans.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to(plans_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper

  def pp(text = '')
    text = text.to_s
    rows = text.split("\n").count
    raw text_area_tag('post', text, :size => "35x#{rows}", :wrap => 'off')
  end

  def format_date(date)
    "#{week_day(date)} (#{date.strftime("%d/%m/%Y")}):"
  end

  def week_day(date)
    if date.today?
      'Today'
    elsif (date + 1.day).today?
      'Yesterday'
    else
      date.strftime("%A")
    end
  end

  def pretty_text(text, delimiter = "\n")
    text = text.to_s
    lines = text.split("\n")
    lines.delete_if{|line| line.strip.blank?}
    lines.join(delimiter)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A-Team Work Log</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override" %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">A-Team Work Log</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <!-- <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li> -->
          <li><%= link_to t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path, :method => :delete %></a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
          <li class="first <%= 'active' if controller.is_a?(PlansController)%>"><%= link_to "Plans", dashboard_plans_path%></li>
          <li class="<%= 'active' if controller.is_a?(ReportsController)%>"><%= link_to "Reports", reports_index_path%></li>
        </ul>
      </div>
    </div>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> A-Team Work Log.</p>
          </div>
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A-Team Work Log</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/plans/_form.html.erb
  <div class="group">
    <%= f.label :date_for, t("activerecord.attributes.plan.date_for", :default => "Date for"), :class => :label %>
    <%= f.date_select :date_for, :class => 'date_select' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :actual_log, t("activerecord.attributes.plan.actual_log", :default => "Actual log"), :class => :label %>
    <%= f.text_area :actual_log, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :report_log, t("activerecord.attributes.plan.report_log", :default => "Report log"), :class => :label %>
    <%= f.text_area :report_log, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :extra_hours, t("activerecord.attributes.plan.extra_hours", :default => "Extra Hours"), :class => :label %>
    <%= f.text_area :extra_hours, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), plans_path, :class => "text_button_padding link_button" %>
</div>

app/views/plans/_sidebar.html.erb
<!-- <div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div> -->
<div class="block">
  <h3>Reports</h3>
  <ul class="navigation">
    <li><%= link_to "Today", dashboard_plans_path(:format => :txt), :target => :blank %></li>
  </ul>
</div>

app/views/plans/dashboard.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.dashboard", :default => "Dashboard")}", dashboard_plans_path  %></li>
      <li class=""><%= link_to "#{t("web-app-theme.my_plans", :default => "My Plans")}", plans_path  %></li>
      <li class="last"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_plan_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.dashboard", :default => "Dashboard")  %></h2>
    <div class="inner">
      <%= form_for :plans, :url => multiple_update_plans_path, :html => { :class => :form } do |f| -%>
        <ul class="list">
          <% @plans.each do |plan| %>
            <%= f.fields_for plan.id.to_s, plan do |plan_fields| %>
              <li>
                <div class="left">
                  <h3><%= week_day(plan.date_for) %></h3>
                  <%= l(plan.date_for, :format => :short) %>
                </div>
                <div class="item">
		              <h4>Actual Log</h4>
                  <%= plan_fields.text_area :actual_log, :size => '70x5' %>
                  <% if plan == @plans.first %>
                    <h4><%= link_to_function "Report Log", "$('##{dom_id(plan, :report_log)}').toggle();"%></h4>
                    <%= plan_fields.text_area :report_log, :size => '70x5', :style => 'display:none', :id => dom_id(plan, :report_log) %>
                    <h4><%= link_to_function "Extra Hours", "$('##{dom_id(plan, :extra_hours)}').toggle();"%></h4>
                    <%= plan_fields.text_area :extra_hours, :size => '70x5', :style => 'display:none', :id => dom_id(plan, :extra_hours) %>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
        <div class="group navform wat-cf">
          <button class="button" type="submit">
            <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.update", :default => "Update")}") %> <%= t("web-app-theme.update", :default => "Update") %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

<script type="text/javascript">
$(document).ready(function() {
  $("#extra_hours").hide();
});
</script>

app/views/plans/dashboard.txt.erb
Actual Log (skype)

<% @plans.each do |plan| -%>
<%= "Extra Hours:\n#{plan.extra_hours}\n\n" if plan.extra_hours.present? -%>
<%= format_date(plan.date_for) %>
<%= raw pretty_text(plan.actual_log) %>

<% end -%>

----------------------------------------------------

Report Log (campfire)

<% @plans.each do |plan| -%>
<%= "Extra Hours:\n#{plan.extra_hours}\n\n" if plan.extra_hours.present? -%>
<%= format_date(plan.date_for) %>
<%= raw pretty_text(plan.report_log||plan.actual_log) %>

<% end -%>

app/views/plans/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.dashboard", :default => "Dashboard")}", dashboard_plans_path  %></li>
      <li class=""><%= link_to "#{t("web-app-theme.my_plans", :default => "My Plans")}", plans_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_plan_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_plan_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Plan</h2>
    <div class="inner">
      <%= form_for @plan, :url => plan_path(@plan), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/plans/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.dashboard", :default => "Dashboard")}", dashboard_plans_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.work_log", :default => "Work Log")}", plans_path  %></li>
      <li class="last"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_plan_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.actual", :default => "Work")  %> Log</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th><%= t("activerecord.attributes.plan.date_for", :default => t("activerecord.labels.date_for", :default => "Date")) %></th>
          <th class=""><%= t("activerecord.attributes.plan.actual_log", :default => t("activerecord.labels.actual_log", :default => "Actual log")) %></th>
	  <th>Report log</th>
	  <th class="actions">Actions</th>
        </tr>
        <% @plans.each do |plan| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= link_to plan.date_for, plan %></td>
          <td><%= raw pretty_text(plan.actual_log, "<br/>") %></td>
	  <td><%= plan.report_log.present? ? 'Yes' : 'No'%></td>
	  <td><%= link_to 'Edit', edit_plan_path(plan) %> | <%= link_to "Delete", plan, :method => :delete, :confirm => 'Are you sure?' %></td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>

        <%= will_paginate @plans  %>

      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/plans/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.dashboard", :default => "Dashboard")}", dashboard_plans_path  %></li>
      <li class=""><%= link_to "#{t("web-app-theme.my_plans", :default => "My Plans")}", plans_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_plan_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Plan</h2>
    <div class="inner">
      <%= form_for :plan, :url => plans_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/plans/overview.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.overview", :default => "Overview")}", overview_plans_path  %></li>
    </ul>
  </div>
  <div class="content">
  <%= form_for :plans, :url => multiple_update_plans_path, :html => { :class => :form } do |f| -%>
    <% @users.each do |user|%>
      <h2 class="title"><%= user.name %></h2>
      <div class="inner">
        <ul class="list">
          <% user.plans.last_two.each do |plan| %>
            <%= f.fields_for plan.id.to_s, plan do |plan_fields| %>
              <li>
                <div class="left">
                  <h3><%= week_day(plan.date_for) %></h3>
                  <%= l(plan.date_for, :format => :short) %>
                </div>
                <div class="item">
                  <%= plan_fields.hidden_field(:user_id, :value => user.id) unless plan.persisted? %>
                  <%= plan_fields.text_area :actual_log, :size => '34x5', :style => "float:left"%>
                  <%= plan_fields.text_area :report_log, :size => '34x5', :value => plan.report_log? ? plan.report_log : plan.actual_log %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="group navform wat-cf">
        <button class="button" type="submit">
          <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.update", :default => "Update")}") %> <%= t("web-app-theme.update", :default => "Update") %>
        </button>
      </div>

  <% end %>
</div>
</div>

app/views/plans/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.dashboard", :default => "Dashboard")}", dashboard_plans_path  %></li>
      <li class=""><%= link_to "#{t("web-app-theme.my_plans", :default => "My Plans")}", plans_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_plan_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", plan_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      <h3><%= l(@plan.date_for, :format => :long) %></h3>
        <p>
          <b><%= t("activerecord.attributes.plan.actual_log", :default => t("activerecord.labels.actual_log", :default => "Actual log")) %>:</b><br/>
          <pre><%= @plan.actual_log   %></pre>
        </p>

        <p>
          <b><%= t("activerecord.attributes.plan.extra_hours", :default => t("activerecord.labels.extra_hours", :default => "Extra hours")) %>:</b><br/>
          <pre><%= @plan.extra_hours   %></pre>
        </p>

        <p>
          <b><%= t("activerecord.attributes.plan.report_log", :default => t("activerecord.labels.report_log", :default => "Report log")) %>:</b><br/>
          <pre><%= @plan.report_log %></pre>
        </p>
        <p>
        </p>

      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_plan_path(@plan), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), plan_path(@plan), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/reports/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "Daily plan", reports_index_path %></li>
    </ul>
  </div>
  <div class="content">
  <%= form_for :plans, :url => multiple_update_plans_path, :html => { :class => :form } do |f| -%>
    <% @users.each do |user|%>
      <h2 class="title"><%= user.name %></h2>
      <div class="inner">
        <ul class="list">
          <% user.plans.last_two.reverse.each do |plan| %>
            <%= f.fields_for plan.id.to_s, plan do |plan_fields| %>
              <li>
                <div class="left">
                  <h3><%= week_day(plan.date_for) %></h3>
                  <%= l(plan.date_for, :format => :short) %>
                </div>
                <div class="item">
                  <%= plan_fields.hidden_field(:user_id, :value => user.id) unless plan.persisted? %>
                  <%= plan_fields.text_area :actual_log, :size => '34x5', :style => "float:left"%>
                  <%= plan_fields.text_area :report_log, :size => '34x5', :value => plan.report_log? ? plan.report_log : plan.actual_log %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="group navform wat-cf">
        <button class="button" type="submit">
          <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.update", :default => "Update")}") %> <%= t("web-app-theme.update", :default => "Update") %>
        </button>
      </div>

  <% end %>
</div>
</div>